import Head from "next/head";
import React from "react";
import { Navbar } from "../Navbar";
import styles from "./MainLayout.module.css";

type Props = {
    children: JSX.Element | JSX.Element[]
}

export const MainLayout = ({children}: Props) => {
  return (
    <>
      <Head>
        <title>Miguel Herrera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        {children}
      </main>
    </>
  );
};
